### ISSUE TITLE
Lag with qeeqez color profile

### ISSUE THREAD

**Issue by alexmenn** [stevezhengshiqi/XiaoMi-Pro#12]
Hi! It's very strange. I've installed the new color profile to have better SRGB in screen, but if I apply it, all in my system are laggy. Chrome is very laggy when scrolling some pages, and UI in OS X too.

This is the color profile I mean: https://github.com/stevezhengshiqi/XiaoMi-Pro/issues/7

Am I the only one having this issue?

**Comment by stevezhengshiqi** [comment]
It's strange. Theoretically, color profile won't affect system performance. Maybe you open the HiDPI which causes this problem?

**Comment by alexmenn** [comment]
No, I dont use the HiDPI solution, im fine with fullhd resolution. It so strange, I know...

**Comment by alexmenn** [comment]
After installing hidpi script, the color profile seems to work ok. So strange...

**Comment by alexmenn** [comment]
The lag persists with new color profile. But just in Chrome... Any idea? anyone can check this?

**Comment by alexmenn** [comment]
Ok!! the problem was in Chrome. I set Chrome colorprofile and forced it to sRGB and works perfect. 

chrome://flags/#force-color-profile
![captura de pantalla 2018-09-19 a las 19 37 17](https://user-images.githubusercontent.com/42182041/45770721-749bd300-bc43-11e8-8867-dff3cc4cbee6.png)

**Comment by javmain** [comment]
it's work.thx @alexmenn

**Comment by stevezhengshiqi** [comment]
Solved in the latest profile in https://github.com/daliansky/XiaoMi-Pro/tree/master/Color%20Profile.
