### ISSUE TITLE
Internal Microphone not working.

### ISSUE THREAD

**Issue by alexandrejacarvalho** [stevezhengshiqi/XiaoMi-Pro#13]
Hi, I've installed my macOS yesterday and I've do all the normal installation process, updated all the stuff, and fix all the bugs, except the internal microphone is still not working.

As someone having the same problem?

Thank you for the great work @stevezhengshiqi and all the people who helped!

**Comment by stevezhengshiqi** [comment]
@AlexCarvalhoDev Hi, for your internal microphone, you can try inject id 28 in `config.plist`.

- Use `Text Editor.app` to open `/EFI/CLOVER/config.plist`
- Find the following code
`<key>Audio</key>
		<dict>
			<key>Inject</key>
			<integer>99</integer>`
- Replace with this:
`<key>Audio</key>
		<dict>
			<key>Inject</key>
			<integer>28</integer>`
- Restart and see whether it works

**Comment by AlexCarvalhoDev** [comment]
Yes, It works!

Thanks for your time!

**Comment by wisper-shadow** [comment]
I have installed Mojave with version 1.2.8, and I followed the #7 to fix the internal microphone error, but when I insert my headphones, the internal microphone doesn't work again, can you help me with that problem?

**Comment by stevezhengshiqi** [comment]
@wisper-shadow Sorry for delay. I will check it when I come home. Recently I am preparing for the SAT test.

**Comment by yehao76** [comment]
Hello, my device is i7 and 16g
my mircophone on my device is working fine(with no headphone pulg)
but it couldn't work if i plug my headphoe(I can listen,but I CAN'T SPEAK)
THANKS FOR YOUR GREAT WORK!

**Comment by stevezhengshiqi** [comment]
Hi, you can try layout-id 30. @yehao76 
* Use `Text Editor.app` to open `/EFI/CLOVER/config.plist`
* Find the following code:
  `<key>layout-id</key> <integer>99</integer>`
* Replace with this:
  `<key>layout-id</key> <integer>30</integer>`
* Restart

**Comment by yehao76** [comment]
> Hi, you can try layout-id 30. @yehao76
> 
> * Use `Text Editor.app` to open `/EFI/CLOVER/config.plist`
> * Find the following code:
>   `<key>layout-id</key> <integer>99</integer>`
> * Replace with this:
>   `<key>layout-id</key> <integer>30</integer>`
> * Save and restart

**Comment by yehao76** [comment]
wow！
It works!THANKS FOR YOUR TIME!
