### ISSUE TITLE
Second USB Type C port not working.

### ISSUE THREAD

**Issue by AlexCarvalhoDev** [stevezhengshiqi/XiaoMi-Pro#15]
Hi, I've tried to use the second USB C port (not the charging port) and It din't work.
The charging port works perfectly.

Do I need to activate it in some way?

Best regards.

Btw, thank you @stevezhengshiqi for your awesome support!

**Comment by stevezhengshiqi** [comment]
Hi, my second USB C port works great. Could you send me a trouble shooting? I need a ioreg file generated by `IORegExplorer` and your Clover folder.(Plug the U disk into the second USB C port when you generate the ioreg file)
[IORegistryExplorer.app.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2394758/IORegistryExplorer.app.zip)

**Comment by AlexCarvalhoDev** [comment]
Sorry for the long wait answer, I don't have a  U disk. I'm connecting a USB C to HDMI adapter and is not working. Should I do the same troubleshooting anyway?

Regards!

**Comment by qeeqez** [comment]
Second USB-C is only for usb devices.
Only first usb-c can charge and act like HDMI
p.s. it's not macOS specific, it's Xiaomi Pro's port limitation.

**Comment by AlexCarvalhoDev** [comment]
Ok, so this Issue is not really a Issue :P I need to buy a dongle to use the same port for hdmi and charging.
Thank you anyway for all your help!
