### ISSUE TITLE
我是隔壁小米游戏本八代的

### ISSUE THREAD

**Issue by chuntaojun** [stevezhengshiqi/XiaoMi-Pro#16]
小米游戏本在10.13版本可以驱动触控板，但是升级到10.14后就没办法驱动。有大佬已经按照亚历山大作者的说明更改了适配，使得小米游戏本可以在10.13版本上驱动触控板，但是一旦升级到10.14就崩溃了，所以我想来问问，您的小米pro笔记本的触控板驱动底层信息可以告诉我吗？

**Comment by stevezhengshiqi** [comment]
你好，我已经对亚历山大作者的驱动进行了修改，使得驱动适配14，但不保证所有机型都能正常工作。驱动在https://github.com/alexandred/VoodooI2C/issues/70 。有2.0.3和2.1两个版本，都可以试试。

**Comment by chuntaojun** [comment]
好的，我去试下，如果又问题能再请教吗

**Comment by stevezhengshiqi** [comment]
嗯，互帮互助，有时间我尽量解答。

**Comment by chuntaojun** [comment]
万分感谢

**Comment by chuntaojun** [comment]
昨天遇到了一个编译问题，
`Access width of Field Unit extends beyond region limit`

错误代码如下
`Field (OGNS, DWordAcc, NoLock, Preserve)
    {
        Offset (0x1000), 
        ECOK,   8, 
        OPR0,   8, 
        OPR1,   8
    }`

网络上是说修改DWordAcc，我修改成AnyAcc后编译通过，但是编译保存替换原来的DSDT后还是不行，但是另一个人却成功了，我想问下我那样修改正确吗

**Comment by stevezhengshiqi** [comment]
我也不太清楚你遇到的这个编译问题。可以发一份原DSDT和要修改的内容过来探讨一下。

**Comment by chuntaojun** [comment]
[DSDT.aml.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2403878/DSDT.aml.zip)

**Comment by stevezhengshiqi** [comment]
这个错误好像可以通过修改DWordAcc -> AnyAcc/ByteAcc, 或者扩大`OperationRegion (OGNS, SystemMemory, 0x7BC40018, 0x00001003)`里申明的长度。

既然你修改了DwordAcc无效，我尝试了另外一个方式，把`0x00001003`改成了`0x00001005`,可以通过编译。
[DSDT.aml.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2403902/DSDT.aml.zip)

**Comment by stevezhengshiqi** [comment]
@gujiangjiang 我已经做好2.1.1 10.14版了，小米Pro完美支持。
![2018-09-19 9 01 30](https://user-images.githubusercontent.com/36894554/45864497-bd22d000-bdac-11e8-9b42-8bd7eacaadeb.png)
[VoodooI2C v2.1.1.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2404193/VoodooI2C.v2.1.1.zip)

**Comment by gujiangjiang** [comment]
他这个USB是什么情况？没看懂，触屏还是触摸板的USB？

**Comment by stevezhengshiqi** [comment]
@gujiangjiang 2.1的触控板会识别为magic trackpad外界触控板，2.1.1通过修改id会让系统识别为内置触控板。这个修复在13生效，14无效。

**Comment by chuntaojun** [comment]
> @gujiangjiang 2.1的触控板会识别为magic trackpad外接触控板，2.1.1通过修改id会让系统识别为内置触控板。这个修复在13生效，14无效。

小米游戏本也是这个问题吗

**Comment by gujiangjiang** [comment]
@stevezhengshiqi 测试成功，目前睡眠不会自动重启了，重启也不会出现五国了，但是可能是我机器的问题，我习惯点按，不是轻触，但是这个明显点按很容易失灵，明明按下去了，但是没反应，轻触很灵敏，看来我得改变习惯了。
USB那个估计得等作者修复了，毕竟作者说这个目前还不支持10.14，估计他还没升级到10.14，等正式版出来苹果应该会开放内核源代码估计就有解了。
先谢啦

**Comment by gujiangjiang** [comment]
对，老版本支持的还可以，2.1开始奇奇怪怪的，点按按2次成功1次，差不多这样

**Comment by stevezhengshiqi** [comment]
@chuntaojun 这里有四个DSDT，你可以逐一尝试，记得测试每个DSDT的时候要更名成DSDT。不保证工作，都不行的话我再想办法。
[DSDT.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2404403/DSDT.zip)

**Comment by chuntaojun** [comment]
> @chuntaojun 这里有四个DSDT，你可以逐一尝试，记得测试每个DSDT的时候要更名成DSDT。不保证工作，都不行的话我再想办法。
> [DSDT.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2404403/DSDT.zip)

谢谢您了，我今天看了快一个白天的那个问题了，还有一个显卡的问题都还没解决 T T

**Comment by stevezhengshiqi** [comment]
@chuntaojun 加油，黑苹果的路很艰辛，但也会有些小成就感。

**Comment by chuntaojun** [comment]
> @chuntaojun 加油，黑苹果的路很艰辛，但也会有些小成就感。

替换DSDT以及安装了kext驱动，全部凉凉，我再去多看看

**Comment by johnnync13** [comment]
https://github.com/alexandred/VoodooI2C/releases/tag/v2.1.1 can you modify to Mojave?

**Comment by stevezhengshiqi** [comment]
这个问题不适合在小米Pro的github里，关闭了。
