### ISSUE TITLE
[NEWBIE] Can't progress to post-installation, reboots back to clover

### ISSUE THREAD

**Issue by Romyeo** [stevezhengshiqi/XiaoMi-Pro#17]
Hello Steveee,

I'm all day reading the forums here: 
by Razorkey
https://www.tonymacx86.com/threads/guide-xiaomi-mi-notebook-pro-high-sierra-10-13-6.242724/ 

also here:
by _Dusty_
https://www.reddit.com/r/hackintosh/comments/7amizy/guide_installing_macos_high_sierra_on_the_mi/

And i can't seem to make it work. I was able to go into the installation via USB but after booting to the post-installation part, the loader moves then reboots to the Clover Boot Menu.

Steps that I did.

1. Create Bootable USB, downloaded the latest high-sierra install image using high sierra patcher.
2. Run the commands using the guide post of _Dusty_.
3. Installing clover. I did this in two ways. the first way doesn't seem to work.

[First way]:
3.1.1 Install clover using CLOVER EFI v2.4 -  r4674
3.1.2 Clicked continue -> continue, selected my usb where the installer is downloaded.
3.1.3 Clicked Customized, Ticked Options:

```
[ * ] Clover for UEFI Booting only
[ * ] Install Clover in the ESP
[ - ] UEFI Drivers
      [ * ] AppleImageCodec-64
      [ * ] AppleKeyAggregator-64
      [ * ] AppleKeyFeeder-64
      [ * ] AppleUITheme-64
      [ * ] DataHubDxe-64
      [ * ] FirmwareVolume-64
      [ * ] FSInject-64
      [ * ] SMCHelper-64
      [ * ] VBoxHfs-64
```

3.1.3 EFI Mount showed up, copied Xiaomi-Pro/EFI -> EFI Mount -> Merge All. I used both your EFI Setup, and also @daliansky EFI Setup in two different installation, both didn't work.

Problem: When booting on the Install MacOS High Sierra Installer etc. It just shows the apple logo then reboots back to the CLOVER menu.

Question: Should i merge all or replace?

[Second Way]:
3.2.1 I didn't install clover, instead i used Clover Configurator -> Mount EFI -> Mount EFI partition of bootable usb installer -> EFI Mount showed up.
3.2.2 Copied Xiaomi-Pro/EFI -> EFI Mount.
I used also both your EFI Setup and also @daliansky EFI Setup, also in different installation. This one worked.

4. I was able to boot to the installation usb, formatted the ssd to MacOS Journaled -> next -> install on this ssd -> installing on ssd.

Question: Should it just reboot automatically when installing? Because when it was installing on the usb it reboots back to the CLOVER Boot menu automatically after 2 minutes mark i think, even the loader wasn't able to reach the end bar. Then the install MacOS shows now on the CLOVER Boot menu.

5. Selected install MacOS etc. It boots up, shows the apple logo, shows the message 'Installing, will be done after 18mins' something like that i forgot. But it just reboots back to the CLOVER Boot menu after 10 seconds or so.

Did i miss something?
Thank you

**Comment by stevezhengshiqi** [comment]
Hi, first, you have to delete origin `BOOT` and `CLOVER` folders in EFI partition(both in U disk and SSD) and then copy these two folders from the latest Github release.

Second, make sure your SSD is not a PM981.

By the way, for post-installation question, you can ask Rehabman in tonymacx86 for professional help.

**Comment by Romyeo** [comment]
Hey thanks for the quick reply @stevezhengshiqi,

Alright will do just that.
I'm currently using the default SSD that comes with the xiaomi notebook pro 16gb variant.

Alright will ask the thread.
Thanks

**Comment by stevezhengshiqi** [comment]
As the `README.md` says, Xiaomi Pro uses `PM981` in some models. You need to check the serial number. `PM981` are not fully supported by this EFI.

**Comment by Romyeo** [comment]
Thanks for the heads up @stevezhengshiqi 

You were right, sorry about the README.md, didn't read it clearly. I checked my SSD serial and my model was the MZVLB - PM981. Is there a way to support this or a different route I could take? thanks

**Comment by stevezhengshiqi** [comment]
I think currently there's no perfect solution. You can search for more information about this SSD in mackintosh forum; and the solution in the link provided in README.md may work.(probably not). 

The best solution is to replace SSD to a supported one.
