### ISSUE TITLE
Laptop screen turns black when connect HDMI

### ISSUE THREAD

**Issue by AlexCarvalhoDev** [stevezhengshiqi/XiaoMi-Pro#20]
Hi!

A few weeks ago I connect my second monitor via HDMI port and all was fine.
In the next boot my computer screen turned black and now I can't use the HDMI port because every time I connect it the laptop screen turns black (the external monitor works). 
I've tested a lot of stuff in the past few weeks but nothing worked.
I tried to replace the EFI folder but didn't work too.

I hope you can help me :)

**Comment by stevezhengshiqi** [comment]
@AlexCarvalhoDev Hi, you can not boot with HDMI connected. And also please read README, 

> Use HDMI port on the left side may cause black internal display, please try to reopen the lid.
