### ISSUE TITLE
Audio jack doesn't work after Mojave update

### ISSUE THREAD

**Issue by alexandrejacarvalho** [stevezhengshiqi/XiaoMi-Pro#21]
Hi,

After the macOS Mojave update my audio jack didn't work anymore.
Tried to replace the EFI folder and nothing changed.

Thank you for all the help with theses issues!

**Comment by stevezhengshiqi** [comment]
@AlexCarvalhoDev Hi, please reinstall ALCPlugFix after every installation.

P.S You can discuss all these small questions in tonymacx86. I am more willing to see constructive issues.

**Comment by AlexCarvalhoDev** [comment]
Thank you for you answer. Sorry for this annoying issues, but before I post them here I search and I didn't find the solution for this.

Regards.

**Comment by stevezhengshiqi** [comment]
@AlexCarvalhoDev Hi, have you tried to reinstall ALCPlugFix?

**Comment by AlexCarvalhoDev** [comment]
Yes, installed it and reboot the pc.
The problem continues.

**Comment by stevezhengshiqi** [comment]
@AlexCarvalhoDev Have you also tried to replug the earphone?

**Comment by AlexCarvalhoDev** [comment]
@stevezhengshiqi Yes, of course :)

**Comment by stevezhengshiqi** [comment]
Then I have no idea currently. Mine works well. By the way, you can list all what you have dione in the first place to save our time.

**Comment by FallenChromium** [comment]
Mine works well too. @AlexCarvalhoDev which laptop version you have, i5 or i7?

**Comment by AlexCarvMobipium** [comment]
Hi @stevezhengshiqi and @FallenChromium.
When I get home today i will test it again, and do a full report of my problems.
My laptop is the i7 version with 16GB of RAM.

**Comment by AlexCarvalhoDev** [comment]
Hi @stevezhengshiqi and @FallenChromium.
When I get home today i will test it again, and do a full report of my problems.
My laptop is the i7 version with 16GB of RAM.

**Comment by AlexCarvalhoDev** [comment]
Hi, 

Sorry for the delay.
Today I checked the headphone jack again and it works, but is very very low volume (I need to have the music in the max volume to can hear).
Do you know a fix for this?

Regards.
