### ISSUE TITLE
Trackpad right click

### ISSUE THREAD

**Issue by shyim** [stevezhengshiqi/XiaoMi-Pro#22]
Hey,

thank you for your Configuration. But i cannot make a Right Click. I showed also the Trackpad Options in System Settings and the right click is there activated. 
![bildschirmfoto 2018-10-14 um 12 27 17](https://user-images.githubusercontent.com/6224096/46915490-9ec78300-cfac-11e8-95c9-5af377b77e01.png)

Have i missed something?

**Comment by stevezhengshiqi** [comment]
Hi, You have to check the third option and use two fingers to activate right key.

**Comment by shyim** [comment]
I have currently the two finger tap activated and it does not work. Have i to update Voodooi2C?

**Comment by stevezhengshiqi** [comment]
I recommend to set trackpad like this and uncheck `Smart Zoom`
![screen shot 2018-10-14 at 23 03 21](https://user-images.githubusercontent.com/36894554/46918496-7324b700-d005-11e8-891e-9e4178e631c6.jpg)

**Comment by stevezhengshiqi** [comment]
Can you make sure you have unchecked `Smart Zoom`? If you have, then I don't have idea about your trackpad.
