### ISSUE TITLE
Trackpad

### ISSUE THREAD

**Issue by johnnync13** [stevezhengshiqi/XiaoMi-Pro#4]
The Spanish community tell me that the trackpad does not work well in your latest version but the click works well.
I modify your last version what It works well (although the click not works very well )with whatevergreen fix.
[EFI_XIAOMI-PRO_7-17-2018 2.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2258436/EFI_XIAOMI-PRO_7-17-2018.2.zip)

**Comment by stevezhengshiqi** [comment]
Hi, I am using my latest release for a week, and I don't find any problem on the trackpad. Could I get a trouble shooting file from your friends?

**Comment by johnnync13** [comment]
I can say that there aren't any problem
