### ISSUE TITLE
How do you set Brightness keys?

### ISSUE THREAD

**Issue by johnnync13** [stevezhengshiqi/XiaoMi-Pro#5]
I have to do on my Xiaomi Notbook 12. I think that I have to follow your stepts with LGPA.aml. But I don't know how I have to change, and obtain hexadecimal numbers of keyboard

**Comment by stevezhengshiqi** [comment]
I followed the instructions(Brightness key part) [here](https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/). First, you have to find out your brightness keys are handled by PS2 or ACPI. The methods are very different.

**Comment by johnnync13** [comment]
agree. I just bought a xiaomi my laptop air with 87550u. The fact is that I detected the ssd as external and at the time of mounting the preboot apfs to carry out the installation I get an error. I thought that being practically the same hardware as the xiaomi notebook Pro, you could help me.

**Comment by stevezhengshiqi** [comment]
Are you using a PM981 SSD? It seems like PM981 doesn't support MacOS very well.

**Comment by johnnync13** [comment]
Yes, I'm using pm981

**Comment by stevezhengshiqi** [comment]
The solution in https://www.tonymacx86.com/threads/how-to-fix-pm981-in-10-13-3-17d47.245063/ might work, but PM981 still cashes frequently after installation. My personal suggestion is replace SSD with a supported one.

**Comment by johnnync13** [comment]
Works in mojave? I'm building EFI on beta 10

**Comment by stevezhengshiqi** [comment]
You can read instructions in 
https://www.tonymacx86.com/threads/how-to-fix-pm981-in-10-13-3-17d47.245063/. 
- First install `ACPIDebug.kext` and add DSDT patch in DSDT. 
- Then open system.log and find corresponding log when you press the key.
- After that further implement the DSDT until you find the exact line which take charge of the brightness key.
- At last replace with correct brightness patch. 
Believe me, the instruction from Rehabman describes the details much better than me.

**Comment by johnnync13** [comment]
Now works perfectly. I use ssdt-rmdt and my keyboard reference is KBD0.
