### ISSUE TITLE
Trackpad under 10.14?

### ISSUE THREAD

**Issue by PavelLJ** [stevezhengshiqi/XiaoMi-Pro#6]
Hello @stevezhengshiqi! I tried new folders under macOS Mojave latest beta, but it turns out that Mojave throws KP on VoodooI2C MT2 spoof version of kext. If you have any information about that problem or newer version of the kext, it would be really nice if you would share. Also i wanted to know if I can PM you somehow except QQ/WeChat.

**Comment by stevezhengshiqi** [comment]
The VoodooI2C MT2 spoof version won't work in Mojave, so I separate the `Other` kext folder into `10.13` and `10.14`. I haven't heard any news that alex is working on this project, but it seems like [hieplpvip](https://github.com/hieplpvip/VoodooI2C/tree/native) is trying. You can use glitter to connect him. If there's any news about MT2 spoof version in Mojave, please share and thank you ^_^.

**Comment by FallenChromium** [comment]
I'd like to revive this issue as Mojave release is coming soon, we should be aware of the trackpad driver state. Stock VoodooI2C works really awful, I can't use it.
P.S It's @PavelLJ, I created a new account. If it's not hard for you, rewrite Credits please

**Comment by stevezhengshiqi** [comment]
I can try to work on VoodooI2C to let it work better in Mojave. 

P.S Sure, rewrite Credit is easy. I want to make sure you are @PavelLJ. Can you use that account to send a confirm message here?

**Comment by PavelLJ** [comment]
@stevezhengshiqi Yeah, sure. That's me :)

**Comment by FallenChromium** [comment]
Lmao, i wrote that and deleted account, so it's not visible was it me or not :( I guess my nick is persisted in mail notification

**Comment by stevezhengshiqi** [comment]
@FallenChromium Solved. You can try release v1.2.7 from both daliansky and me.

**Comment by FallenChromium** [comment]
@stevezhengshiqi For real? I mean, is MT2 spoof version working? I tried 1.2.7 release when it's came out with SSDT-ELAN, no luck. Anything I missed?

**Comment by stevezhengshiqi** [comment]
@FallenChromium Yes, it works. SSDT-ELAN has nothing to do with our trackpad. I edited the 1.2.7 release about six hours ago. You can have a try.

**Comment by FallenChromium** [comment]
@stevezhengshiqi Awesome! How did you do that? What did you changed in the source code to have it not panic on Mojave? My friend wrote some commits for MT2 version which have palm rejection thanks to VoodooPS2Controller implementation

**Comment by stevezhengshiqi** [comment]
@FallenChromium Nice, extremely look forward to that. These are the things I did:

- First, I cloned the native branch from [hieplpvip](https://github.com/hieplpvip/VoodooI2C/tree/native) . It has newest sub satellite kexts.

- Then, I changed the source code according to [goodwin's fork](https://github.com/goodwin/VoodooI2C/commit/8d9fff18a00c562095b7d96c3726f52e1c55418d) to avoid KP during shut down. I think this step is unnecessary.

- After that I edited the source code according to [#70](https://github.com/alexandred/VoodooI2C/issues/70).

If you want, I can share my source code.

**Comment by FallenChromium** [comment]
@stevezhengshiqi  Oh i see. Thanks for pointing to this issue, didn't found it before. By the way macOS Golden Master should be released soon (for now I didn't found info about that) and I think based on that workaround @alexandred would commit appropriate changes to native branch. I think I'll wait until that moment. By the way trackpad is awesome, thanks for building this kext for us.
