### ISSUE TITLE
Bluetooth not working with Taobao card

### ISSUE THREAD

**Issue by MrJosu** [stevezhengshiqi/XiaoMi-Pro#7]
Hi, i successfully installed wifi card from Taobao, but i cannot manage to run bluetooth. Any advice in this?

**Comment by stevezhengshiqi** [comment]
Please provide your wifi card model or the link of the card.

**Comment by MrJosu** [comment]
@stevezhengshiqi Card model is BCM943602CS and bought it from https://item.taobao.com/item.htm?_u=u32prbov071e&id=532197802538

**Comment by stevezhengshiqi** [comment]
Great. You are using the same model as mine. Did you solder D+ and D- wire into pin4 and 5 in WLAN_LTE slot?

**Comment by MrJosu** [comment]
Yes, wifi is working, but bluetooth no chance :(

**Comment by stevezhengshiqi** [comment]
Did you solder your D+ and D- wire?

**Comment by MrJosu** [comment]
yes, right. I will show you image - https://yadi.sk/i/RBLk0UDG3a9j6T

**Comment by stevezhengshiqi** [comment]
It seems OK. I will assume your BT is connected. Go to `EFI/CLOVER/ACPI/patched` and replace `SSDT-USB.aml` with the one below.
[SSDT-USB.aml.zip](https://github.com/stevezhengshiqi/XiaoMi-Pro/files/2280928/SSDT-USB.aml.zip)

**Comment by MrJosu** [comment]
Man, you magician! Thank you so much, i can  enjoy my airpods!!! yahoo

**Comment by MrJosu** [comment]
I think you need mention this in manual :) i know few people bought this thing. Now need to find best place for antennas, to get full speed, now its only 40 perc of maximum

**Comment by stevezhengshiqi** [comment]
OK. I will update README. 

For the antennas, I personally recommend to stick them behind the trackpad(under the battery). They have to be sticked on the top of the trackpad; otherwise the trackpad can't be clicked.

**Comment by MrJosu** [comment]
I stick them under, maybe they facing wrong way. If you will have option and you will open your laptop lid please make picture how you mount them. I with friends help was trying solder them 3 times :D i think we something wrong

**Comment by MrJosu** [comment]
Another think. I can update bios with no issues?

**Comment by MrJosu** [comment]
Only one difference, i have 3 antennas :) What you done with your heatsink?

**Comment by stevezhengshiqi** [comment]
I have 3 antennas too, and one of them is shorter. It is situated in the middle of the trackpad.

**Comment by MrJosu** [comment]
Lol, i was blind

**Comment by shilch** [comment]
I ordered a Xiaomi Notebook Pro for hackintoshing. I heard that the default Intel wifi chip can not be replaced but instead the second M.2 slot can be used to insert a Broadcom chip. I found [this guide](https://www.tonymacx86.com/attachments/xiaomi-mi-notebook-pro-broadcom-wifi-installation-guide-v0-1-pdf.323375/) which uses a BCM94352Z and a E to M Key Adapter to use internal wifi with the hackintosh. However, it is said that Bluetooth does not work.  

Now I have found this thread and have two questions:  
(1) Does the BCM943602CS fit into the M.2 without any adapter? If not, what is the difference to BCM94352Z?  
(2) If I have the BCM943602CS inserted into the M.2 slot, what exactly do I have to do to enable Bluetooth?

Thanks in advance!

**Comment by fuergaosi233** [comment]
I replace `SSDT-USB.aml`,but  i can't use BT.
I can look my BT in usb of system report but it's `No information found` in BT of system report.
![image](https://user-images.githubusercontent.com/22197568/52935287-f3806d80-3393-11e9-95e3-c4e158753292.png)

![image](https://user-images.githubusercontent.com/22197568/52935272-e82d4200-3393-11e9-89a5-d2b1e1926d94.png)

**Comment by Giannidmg** [comment]
which is color the positive cable and which is the negative one?
